### ISSUE TITLE
INCORRECT LOGIC FOR NIGHT CLASSES

### ISSUE THREAD

**Issue by andychang-1** [chrisayoub/UT-Schedule-GCal#1]
A class that starts and ends late in the PMs will not be correctly added.

"W 630 to 930p GDC 2.502" for example will not be added.

**Comment by andychang-1** [comment]
+1

**Comment by chrisayoub** [comment]
Issue should be solved in latest update 1.1.1 , should be published soon at:
https://chrome.google.com/webstore/detail/hehpififbelocikbgneenkbjohinddff/

Can you confirm the bug is fixed for you?

Thanks for the feedback!
